### ISSUE TITLE
Update the Kubernetes Hosting documentation

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1168]
The Kubernetes hosting documentation needs a review. Things that need to be addressed for example

- [x] Determine which is preferred: Dapr CLI or Helm: Across the all topics under hosting/kubernetes - There is conflicting advice between installing/upgrading production clusters with Helm or CLI. We should be clear on what is preferred for production
- [x] https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#tracing-and-metrics-configuration section is very sparse and does not provide guidance
- [x]  Also include this issue Updating K8s guidance to include app rollout step for when a cluster is completely restarted #1072
- [x] The K8s overview topic and the control plane https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/ need improved wording on how they work and there are broken links in this topic
- [ ] Ideally there should be a script for installing Dapr with production guidance, similar to this https://github.com/mchmarny/dapr-demos/tree/master/setup

**Comment by yaron2** [comment]
> kubernetes-deploy/#install-in-highly-available-mode - This sentence is wrong. Placement is now HA
"You can run Dapr with 3 replicas of each control plane pod with the exception of the Placement pod in the dapr-system namespace for production scenarios."

This is fixed with https://github.com/dapr/docs/pull/1220

> kubernetes-production/ topic

> Does not mention HA mode as being preferred for production.

This is mentioned here: https://v1-rc3.docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#cluster-capacity-requirements

> Also include this issue Updating K8s guidance to include app rollout step for when a cluster is completely restarted #1072

This is mentioned as the last step here: https://v1-rc3.docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/

**Comment by msfussell** [comment]
Also see https://github.com/dapr/docs/issues/1506

**Comment by msfussell** [comment]
This issues is now complete.  It is too opinionated to have a one size fits all for the production guidance.
