### ISSUE TITLE
Add GitHub check for spelling

### ISSUE THREAD

**Issue by daixiang0** [dapr/docs#1649]
I would like to introduce a spelling tool to do spell lint, it would help Improve document quality and help review if possible.

**Comment by orizohar** [comment]
@daixiang0 do you mean adding spell checks to the CI process? Is there a specific tool you have in mind?

**Comment by daixiang0** [comment]
I use https://github.com/client9/misspell for myself, it is pretty good.

**Comment by chrisreddington** [comment]
@daixiang0, @orizohar - Is this still an open issue? I wonder if [GitHub Super Linter](https://github.com/github/super-linter) may be an option. Rather than just doing spell lint, it could also lint any markdown which is created as well.

There is a GitHub action available (I use it on my own blog static site workflow), and it has support for textlint, which relates to natural language. Full list of linters it supports is available [here](https://github.com/github/super-linter).

**Comment by daixiang0** [comment]
Still available, you can pick it @chrisreddington

**Comment by hhunter-ms** [comment]
closing for now - let me know if ready to start working on this and I will reopen.
