### ISSUE TITLE
Update state API reference with TTL

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1676]
https://v1-3.docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/ was created, but we need to update https://v1-3.docs.dapr.io/reference/api/state_api/ to have TTL

See https://v1-3.docs.dapr.io/reference/api/pubsub_api/#metadata for an example

**Comment by msfussell** [comment]
https://github.com/dapr/docs/pull/1626

**Comment by msfussell** [comment]
@berndverst Please update this -  https://v1-3.docs.dapr.io/reference/api/state_api/ to have TTL

**Comment by berndverst** [comment]
@msfussell  There is no metadata section listing other metadata field options on that page. As such there is no good place to add this -- we should be consistent with how this is document in PubSub for example.

Somebody needs to first figure out a structure for comprehensively discussing metadata options for the state store here. At that time I can add `metadata.ttlInSeconds`.

@AaronCrawfis I'm pretty sure I had asked you about this some weeks ago :)

Either way, I see this docs change here as more significant than documenting TTL here. And it's awkward because TTL only applies to some state stores, not all.

How do you want to go about this?

**Comment by msfussell** [comment]
Looking at this more we need to be update the State Management API to include TTL according to this https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/ article, which means is can be set in the metadata value. Add it to the request body for the Save method here https://docs.dapr.io/reference/api/state_api/#request-body

We should also make a note that when using the TTL option, only certain state store support this, according the supported state stores.
