### ISSUE TITLE
Add content for PubSub routing

### ISSUE THREAD

**Issue by pkedy** [dapr/docs#1746]
Add documentation for dapr/dapr#3406.

**Comment by orizohar** [comment]
@pkedy is there a docs PR for this?

**Comment by greenie-msft** [comment]
@msfussell closing this issue since it was addressed in [1.4](https://github.com/dapr/docs/pull/1786) and created a new issue to track adding a dotnet example: https://github.com/dapr/docs/issues/1920

cc: @pkedy

**Comment by ssa3512** [comment]
@pkedy Would it be possible to get clarification in the documentation as to what happens when there is no default route set for pubsub routing? Does dapr just discard the message? Does the message get dead-lettered (if applicable)? Does the message just sit out there forever until a default route is added?
