### ISSUE TITLE
Nats PublishEvent -> topic must be jetstream enabled

### ISSUE THREAD

**Issue by siredmar** [dapr/docs#2001]
**What content needs to be created or modified?**

This page: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-jetstream/

If i follow this page, the PublishEvent will fail with a timeout because the topic was not jestream enabled.

**Describe the solution you'd like**

Please add a hint that the nats topic needs to be jetstream enabled.
e.g.
```
nats stream add <streamname> --subjects <topic>
```

**Where should the new material be placed?**

Right below the `docker run` command.
**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
Resolved

**Comment by NickLarsenNZ** [comment]
@siredmar, as per your change here: https://github.com/siredmar/docs/blob/199e8c0acdb791a04bb074f27b8f0020277f34fd/daprdocs/content/en/reference/components-reference/supported-pubsub/setup-jetstream.md?plain=1#L87

> It is essential to create a NATS JetStream for a specific subject.

Does it have to be for a specific topic (as in `1:1`), or do you just mean there has to be a stream covering the topics you are interested in?

I have created mine like so:

```sh
nats -s localhost:4222 stream add myStream --subjects 'prefix.>'
```

... so that we group together all topics under that prefix into this stream.

- Must it be 1:1, or
- Should the docs be updated to make it clearer, eg:
  - `s/a specific subject/desired subjects/`
  - `nats -s localhost:4222 stream add myStream --subjects 'mySubject,topLevel.>'`
  - Maybe something about careful consideration since streams cannot overlap other streams as I've just found out.

**Comment by siredmar** [comment]
All you need is a stream covering all your subjects you want to publish. This can be a single one or a wildcard subject like you specified e.g. `prefix.>` or a combination of both.
