### ISSUE TITLE
Building Block APIs Docs Refresh

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/docs#2420]
**Description:**
Current docs for the Building Block APIs could use a refresh. Current docs are a bit stale and could use some edits to bring them up to date. This effort will be done over the course of time as bandwidth becomes available. This issue will serve as a record for which docs have already been updated.

**Docs to Refresh:**
- [x] Service Invocation #2419 
- [x] State Management #2463 
- [x] Publish & Subscribe #2413 
- [x] Bindings #2588 
- [x] Secrets
- [ ] Actors (last thing to update here is: #1298)
- [x] Observability #3607 
- [x] Workflow
- [x] Distributed Lock
- [x] Configuration
- [x] Cryptography

**Comment by sicoyle** [comment]
@hhunter-ms Can you add a bit more clarity here in terms of what "refresh means" for the docs that need updating so it is clear on the work that needs to be done please.

**Comment by hhunter-ms** [comment]
@sicoyle Sure - 

Remaining building block doc sets need a "freshness pass", ie:
- Any formatting edits to make consistent with other already "freshened up" building block docs
- General grammar and spelling check
- Check for accuracy (test how-to docs/code snippets)
- Make sure docs explain the concept of the building block well enough for a new user; if need more info, talk to devs in discord channels
- Try adding diagrams to building block overviews that don't currently have one
- If a demo exists in a Dapr community call for that topic, embed at bottom of relevant doc
- Cross link so that users can find all info they need on that topic or the appropriate next steps
