### ISSUE TITLE
Add supported features for all brokers in Pub/Sub broker component spec

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2481]
**What content needs to be created or modified?**

The table shown here https://docs.dapr.io/reference/components-reference/supported-pubsub/ should also display features (such as TTL, supported APIs etc.) supported by each Pub/Sub brokers. 

**Describe the solution you'd like**

To maintain the uniformity we can do something like https://docs.dapr.io/reference/components-reference/supported-state-stores/

**Where should the new material be placed?**

https://docs.dapr.io/reference/components-reference/supported-pubsub/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
This will be affected by this PR change to the docs https://github.com/dapr/docs/pull/2499

**Comment by msfussell** [comment]
@pravinpushkar  - Looking at this, all I see now that due to query metadata options, you can set TTL on all the pub/sub messages as per here https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-message-ttl/. However given this is general to all pub/sub we do not have to have this set on a per component basis.

**Comment by pravinpushkar** [comment]
@msfussell Right, then the Metadata API should also show TTL for all pub/sub components. As of now I am capturing only those components, where TTL is supported natively(dapr does not handle ttl).  Thoughts on this ? 

We can close this issue for now or we can explicitly mention which component supports natively and display a Note for what happens when components does not have a native TTL support. Going forward we might needs this when Batch publish/subscribe comes.

**Comment by greenie-msft** [comment]
@pravinpushkar @msfussell - what are we deciding to do here? It sounds like we first need to address @pravinpushkar's comment on whether the metadata api should only include native TTL support or all pubsub components that Dapr supports since Dapr extends support for TTL.  

We need to close on this for the 1.8 release.

**Comment by pravinpushkar** [comment]
@greenie-msft @msfussell from the metadata API response perspective, we decided in one of the OSS sync to **not** show TTL for any of the Pub/Sub component. This change has been merged for both code and docs repository.

We can close this issue as at the moment there is nothing to update in docs repository.

**Comment by msfussell** [comment]
Not needed
