### ISSUE TITLE
running sample - fail on redis

### ISSUE THREAD

**Issue by codeputer** [dapr/docs#253]
## Expected Behavior

After reading the  ReadMe in ControllerSample, I would hope I could follow the example and have DAPR work as per the instructions.  I'm new to all of this, so I'm hoping I'm missing something that I should have taken into account.  I'm a C# microsoft stack developer no experience (or want) to play with other os, or languages at this poitn.

## Actual Behavior

Dapr SampleController failes on "redispipe.connection".  There is nothing that I can find regarding on redis in this regard - other than I know its storage for state? Redis? I thought DAPR could use Azure resources like CosmosDB, or perhaps Azure Table storage, which can be used locally as well.

## Steps to Reproduce the Problem

dapr environment is setup and running,  curl is installed. pasted in the commands, and it fails.
![DAPR_Failing](https://user-images.githubusercontent.com/611541/68987957-f27a5080-07ec-11ea-8dd0-bcb5d06c1d51.png)

**Comment by jocko-wowza** [comment]
Based on the error, your DAPR application is trying to connect to a Redis server on Localhost.  Are you currently running Redis locally?   

If you don't it's possible that the CLI is injecting some default configurations into your `components/` folder.  

This bug talks about that concern `https://github.com/dapr/docs/issues/254`

If you aren't running Redis locally, you should either delete any default files, or update them to include the connection information for your actual Redis server.

**Comment by codeputer** [comment]
The prerequisites of this example does not specify that redis is required. And or how to install before use.

  Can we specify local azure storage? As this was announced at an MS event, it would make sense that we would have samples from that tech stack.

R

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jocko-wowza** [comment]
Your logs indicate that you're using Redis for PubSub and Statestore.

If you're not using these features, you can remove the component declarations from the `components/` folder.

If you do want to setup Redis, this article exists and discusses how to setup a container, or an Azure cache:
https://github.com/dapr/docs/blob/master/concepts/components/redis.md#configuration

There are also sections for how to configure the Statestore and PubSub.

**Comment by codeputer** [comment]
Thanks very much for being patient with me in regard to these questions, it starting to make sense a bit!

I attempted an Uninstall, and Init of Dapr
[cid:image002.png@01D59D33.F0157A50]

I must be working on the default configuration, as I don't have a component folder.


  1.  Is there a way to view the default configuration, or obtain a copy of the default configuration file for PubSub and Statestore?
  2.  How can I determine if redis is running locally within my configuration?
  3.  Is there an Azure Storage a component configuration for local state store using the local storage service from Azure?
The last line in the documentation you referenced was:
Standalone
By default the Dapr CLI creates a local Redis instance when you run dapr init. However, if you want to configure a different Redis instance, create a directory named components in the root path of your Dapr binary and then copy your redis.yaml into that directory.
Is there a default redis.yaml file, and can it be added as a component directory as opposed to a magic default configuration?

Thanks very much for your time.
Richard

**Comment by jocko-wowza** [comment]
Full disclosure @codeputer -- I'm not a direct contributor to the project, I'm another developer in your position, trying to get it functioning.

To answer your questions as best I can:

1) As I understand it, the components folder determines the configurations for the CLI.   It's possible, that when the CLI doesn't have a components folder, it uses the default configuration.  That's strictly a guess tho.  In my experiences so far, adding the components directory and setting up components configurations for Statestore and PubSub has directed the CLI to use my configurations over any defaults.

2) I have discovered that the CLI/DAPR environment require Redis 5.x or higher because of streaming connection requirements.  Making sure you have the correct version is important. The Redis quickstart has mechanisms to test a local installation of Redis (NOTE: You likely will have to have the DAPR CLI running to test): 
 https://redis.io/topics/quickstart

3) I don't know specifically how to connect to Azure because I'm not directly implementing Azure resources.   The component-contrib repo had descriptions of the various DAPR component implementations.  I have found that these docs are still young, and could use some more details, but it should give you a rough idea of what resources can be used to back which DAPR functionalities:  https://github.com/dapr/components-contrib

**Comment by codeputer** [comment]
Argh!! Found out after hours and hours that the "dapr init" was failing because, Docker was using WINDOW CONTAINERS! Why, why, why cant the init check to see if Docker is in this mode and give an intelligent error message.  I then forked the documentation, and yup, its there - must use Linux containers... but in small print, and after it stays "Install Docker".  As I had Docker installed, I missed that step in the deployment, and hence then also missed the Docker PS command to validate if it's all running or not.

**Comment by yaron2** [comment]
Hey @codeputer, Unfortunately the Docker API or CLI do not have a very good way of telling the daemon mode when running on Windows..

I've opened [this](https://github.com/dapr/cli/pull/208) PR in the CLI docs to make sure it is explicitly stated in the docs.

Thanks for reporting this.
