### ISSUE TITLE
Property shouldn't be translate

### ISSUE THREAD

**Issue by liyehaha** [dapr/docs#2771]
**Describe the issue**
properties for secret scopes (defaultAccess, allowedSecrets, deniedSecrets) in the middle table shouldn't be translate

**URL of the docs**
https://docs.dapr.io/zh-hans/operations/configuration/secret-scope/

**Expected content**

**Screenshots**
![image](https://user-images.githubusercontent.com/7793361/189016816-1956f877-ae12-4d9b-9e00-394e092aca1e.png)

**Additional context**

**Comment by hhunter-ms** [comment]
@AaronCrawfis @msfussell I'm not sure how to fix this - any suggestions?

**Comment by AaronCrawfis** [comment]
The source of this page is here: https://github.com/dapr/docs-zh/blob/794330f6cab2db8e09053bb7bf19233eb3237538/content/zh-hans/operations/configuration/secret-scope.md where the table has the translations.

However, it seems like there has been a lot of changes to the zh-hans translation since this issue was opened, and now the docs translations live over at https://github.com/dapr-cn/docs. Not sure how that's being consumed though, haven't been keeping up to date myself on the translations. @msfussell may know more
