### ISSUE TITLE
Pluggable Component Documentation

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/docs#2799]
**Description:** This issue will be used to track the documentation needed for the Pluggable Components feature targeted for 1.9

**Documentation Needed:**

1.) How to use Pluggable Components
These how-to docs would live in the Operations>Components section under a new section titled "Pluggable Components". We'll have several docs nested underneath.

- [ ] Prerequisites for using Pluggable components
- [ ] What is a pluggable component?
- [ ] How to create a net-new pluggable component?
- [ ] How to set up a Pluggable component (i.e., configure, deploy etc.)
- [ ] Code samples for set up process
- [ ] Using existing pluggable component
- [ ] Invoking pluggable component
- [ ] Using pluggable components with Dapr stand-alone mode
- [ ] Using pluggable components with kubernetes

2.) Updates made in existing docs to accommodate new feature

- [ ] Add pluggable components to the [Components-concept page](https://docs.dapr.io/concepts/components-concept/). Right before _Available Component Types_
- [ ] Entry into [Tutorials table](https://docs.dapr.io/getting-started/tutorials/) 
- [ ] Entry into [Component specs ](https://docs.dapr.io/reference/components-reference/). This will not contain a table ot supported components. It will only include the: _status_ (stable, alpha, beta), _Since_ (Dapr runtime version linked to status), _Component version_  

Related to: #2786

**Comment by mcandeia** [comment]
@nyemade-uversky 

can I propose a few changes ?

I would say that we can get better developers' attention with a section "Developing Components" rather than "Pluggable Components" WDYT? We can explain that the way we have for developing components is either Pluggable or "built-in" and we're going to focus only for Pluggable Components.

Following the same rationale I think the Pre-requisite section should be for "Developing" a pluggable component instead of "using", for using there's no prereq than dapr itself and a hosting environment (k8s or standalone)

Do you think that makes sense to swap the Pre-Requisite section with the "What is a Pluggable Component?", so we can first introduce and if the dev is interested in developing one, we go straight to the prereq section, how about it?

**Comment by msfussell** [comment]
Resolved
