### ISSUE TITLE
Medata setting examples are incorrect

### ISSUE THREAD

**Issue by Kreestyan** [dapr/docs#3353]
**Describe the issue**
The curl examples have a typo and may refer metadata that are not supported. Or least reader should be advised this is only a generic way to pass metadata but it does reflect an actual feature.

**URL of the docs**
https://github.com/dapr/components-contrib/issues/curl%20http:/localhost:3500/v1.0/secrets/vault/db-secret?metadata.version_id=15&?metadata.namespace=production

**Expected content**
Use the '**_?_**' and then '**_&_**' for any consecutive parameters
I don't believe namespace is even a thing today so maybe it's better to use metadata that are currently managed for these examples to avoid any confusion.

**Screenshots**

**Additional context**
This was pointed out when working on issue [#2806](https://github.com/dapr/components-contrib/issues/2806)

**Comment by tmacam** [comment]
Let me add some context:

# Secret stores: Medata setting examples are incorrect 

Documentation on https://docs.dapr.io/reference/api/secrets_api/ presents a CLI example that are known to be broken and is leading users to confusion.

Offending CLI example:

```
curl http://localhost:3500/v1.0/secrets/vault/db-secret?metadata.version_id=15&?metadata.namespace=production
```

Rephrasing from dapr/components-contrib#2806  there are multiple issues with that document:

* The multiple `?` in that URL. That is wrong. :P query parameters are separated by `&`
* That example URL is problematic in multiple ways. I _guess_ it is a made up example that was not even tested and I _guess_ its intent was to show _how_ to provide metadata using the HTTP interface to a hypothetical secret store that supported those features (namespace and versions). But it is an unfortunate one because it is showing features that no secret store currently support at the same time.
   * That URL suggests that we are accessing a HashiCorp Vault component. We do not support namespaces on HashiCorp Vault (yet, this is being addressed on dapr/components-contrib#2806 but even then not as a request metadata).  But we do support versioning on vault.
   * We _do_ [support namespace in k8s secrets](https://github.com/dapr/components-contrib/blob/22fea6f43d53a6dc4780132c8849577928e6ebcf/secretstores/kubernetes/kubernetes.go#L35), but we do not support _versions_** in k8s secrets.


It might be a matter of just replacing `vault` for a generic non-specific component name  -- that would address some of the confusion.

The comments regarding namespace need to be explicit that they are referring to k8s secrets.

**Comment by msfussell** [comment]
@tmacam - It would help if you could suggest and alternative example here and how we can adjust the text for the namespacing

**Comment by hhunter-ms** [comment]
> @tmacam - It would help if you could suggest and alternative example here and how we can adjust the text for the namespacing

@tmacam @msfussell friendly bump

**Comment by tmacam** [comment]
Sorry, this went under the radar. Let me try to fix this.

**Comment by tmacam** [comment]
The PR above was created to address this
