### ISSUE TITLE
Need more information on how to invoke non dapr service using HTTPEndpoint spec

### ISSUE THREAD

**Issue by emalashree** [dapr/docs#3681]
**What content needs to be created or modified?**

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by olitomlinson** [comment]
@emalashree 

Is this information not helpful to you? https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-non-dapr-endpoints/

**Comment by emalashree** [comment]
yes I was able to implement, thank you

**Comment by emalashree** [comment]
I have one doubt, how can we specify the Method url in HTTPRequest Spec flow

**Comment by olitomlinson** [comment]
@emalashree 

I do not believe you can set the Method url in the HTTPRequest spec flow https://docs.dapr.io/reference/resource-specs/httpendpoints-schema/

Are you asking because you need to prevent developers from using certain Methods, or are you asking because you want to hide the Method completely from developers?

**Comment by msfussell** [comment]
@emalashree - Would be interested what you mean, cannot set the method URL. What is missing from here https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-non-dapr-endpoints/#using-an-httpendpoint-resource-or-fqdn-url-for-non-dapr-endpoints and what are you expecting to do?
