### ISSUE TITLE
Distributed Scheduler API building block docs

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3915]
### Jobs pt 1 PR
_merged_ #4164 

- [x] Overview for Jobs API
- [x] Add to conceptual overview
- [x] Add to building blocks concepts
- [x] Update preview feature doc
- [x] Update list of Alpha APIs
- [x] Add API reference doc
- [x] Diagrams
- [x] Update `dapr init` doc to include Scheduler service as included

### Jobs pt 2 PR
_merged_ #4240 

- [x] Jobs API how-to - minor add from README in Go-SDK example PR
- [x] Check formatting and grammar (ie: Jobs overview)

### Jobs pt 3 PR
_in progress_ #4243 

- [x] Screenshot of `dapr init` and `docker ps` output that shows scheduler service is running
- [x] Finish how-to based on future quickstart or example
- [x] Add how to consume a triggered job

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/proposals#44

**Comment by cicoyle** [comment]
Note for myself: the Scheduler will also need to be [documented here](https://docs.dapr.io/concepts/dapr-services/) since its a new control plane service as well.

**Comment by cicoyle** [comment]
This is an involved update and requires updating several documents and diagrams 

Let's just call this the **Scheduler API**, rather than Distributed Scheduler API. All of the APIs are distributed in some way and this term is redundant.

- [x] Overview https://docs.dapr.io/concepts/overview/ This includes updating the diagrams for the control plane for K8s and for VMs  @hhunter-ms - 
- [x] Control plane services  https://docs.dapr.io/concepts/dapr-services/ to add new scheduler service @cicoyle 
- [x] New Scheduler API  https://docs.dapr.io/concepts/building-blocks-concept/ @hhunter-ms 
- [ ] Add developing with Scheduler API https://docs.dapr.io/developing-applications/building-blocks/ @cicoyle 
- [x] Add Scheduler overview https://docs.dapr.io/developing-applications/building-blocks/scheduler/scheduler-overview/
- [ ] Add Scheduler HowTo: https://docs.dapr.io/developing-applications/building-blocks/scheduler/howto-scheduler/ including examples from SDKs. If all examples not created then raising issues in each SDK
- [x] Update the preview feature if needed https://docs.dapr.io/operations/support/support-preview-features/ @ scheduler reminder preview feature config: `SchedulerReminders` @cicoyle 
- [x] Update the list of Alpha APIs https://docs.dapr.io/operations/support/alpha-beta-apis/ @hhunter-ms 
- [x] Add Scheduler API into reference https://docs.dapr.io/reference/api/  including all the APIs with examples @cicoyle 
- [ ] Update Dapr presentation deck https://docs.dapr.io/contributing/presentations/ @marcduiker 
- [x] Update Diagram deck @hhunter-ms 
- [ ] Update go-sdk docs with samples https://docs.dapr.io/developing-applications/sdks/go/go-client/ @cicoyle

**Comment by msfussell** [comment]
Also see this issue in QS repor -  Go SDK Quickstart for Scheduler API https://github.com/dapr/quickstarts/issues/1026

**Comment by cicoyle** [comment]
Adding a TODO here, so I don't forget- thx @olitomlinson for calling this out in discord:

The dapr docs for the new  `Job API` do not  demonstrate how to consume a triggered job in an App - the `OnJobEvent` bits. We should add this

**Comment by hhunter-ms** [comment]
thanks for your help, @cicoyle !!
