### ISSUE TITLE
Workflow backend documentation (workflow state store)

### ISSUE THREAD

**Issue by ASHIQUEMD** [dapr/docs#3924]
**What content needs to be created or modified?**

Documentation related to configuring alternate backend implementations for Dapr Workflow needs to be created.

**Describe the solution you'd like**

The solution involves enabling users to configure alternate backend implementations for Dapr Workflow beyond the default Actors backend. This can be achieved by introducing component config YAML files to specify the backend implementation and its configuration settings.

**Where should the new material be placed?**

The new material should be placed in the Dapr documentation under a section related to Dapr Workflow configuration options.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

PR: https://github.com/dapr/dapr/pull/7283
Proposal: https://github.com/dapr/dapr/issues/7127

**Additional context**

**Comment by msfussell** [comment]
@ASHIQUEMD - This is a required document for v1.13. Please submit a PR. I can work with you to suggest where this should be placed [Attention @cgillum]

**Comment by msfussell** [comment]
These are the topic that need to be update IMO

1) In https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/
 -  Have a "Workflow state stores" sub heading that describe the why and the how you can have alternative workflow state stores described as a component. In this describe the relationship to the actor state store that is used by the actor runtime, and the Placement Service. Mention that Sqlite is an alternative workflow state store and why you would use one over the other (actors are scalable and distributed etc, sql better for local development?)
 
2) In https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/
 - Talk with @cgillum on whether the architecture description and diagram should be update here and this mentioned.
 
3) In https://docs.dapr.io/reference/components-reference/
 - Have a new heading called "Workflow state store component spec"
 - Have component specs for actors (v1.13) and raise a future docs issue to add the sqlite component in v1.14. In the actor component spec is there anything that users can add? Also you can say this is the default that is configured. It is somewhat like the default Name Resolution component for K8s for example (see https://docs.dapr.io/reference/components-reference/supported-name-resolution/nr-kubernetes/) 
 
Feedback: I would have called this type `workflowstatestore.sqlite` rather than `workflowbackend.sqlite`. Backend is vague IMO. Then it would also be`workflowstatestore.actor`. I am going to raise this as a discussion point.

**Comment by ASHIQUEMD** [comment]
@msfussell I have created [the PR for documentation](https://github.com/dapr/docs/pull/4028), please have a look and let me know your feedback.

Regarding architecture description, I checked with @cgillum, and he suggested to add the description and that should be sufficient for the workflow backend.
