### ISSUE TITLE
Issue in Svc-to Svc invocation (dapr->non Dapr) documentation

### ISSUE THREAD

**Issue by creyes432** [dapr/docs#4004]
**Describe the issue**
I am new to dapr, and after reading the documentation and several other resources, I believe there are a couple of issues here:
1) The documentation doesn't accurately describes how to implement this feature. I read all of the links and followed the steps described and I can't get it to work. I created the httpEndpoint.yml file based on the sample provided, double checked appId & methods and I can't get to communicate with the non-dapr service. Dapr returns a 500 error.
2) I would assume this documentation should be applicable to all SDK's (not clear)? I am using **dapr sdk for .NET** and either I am doing something wrong (not properly documented) or the sdk doesn't support this featue. I tried several overrides of the `InvokeMethodAsync` method, and most of them return a 500 error.

![image](https://github.com/dapr/docs/assets/65616166/16d967a0-f7c0-40a4-bf0b-2945b9dbdf5d)

One of the `InvokeMethodAsync` overrides I tested (the one that you pass an HttpRequestMessage, in this case I use the FQDN which dapr doesn't like) returns the exception below:

```
The provided request URI is not a Dapr service invocation URI.
   at Dapr.Client.DaprClientGrpc.InvokeMethodWithResponseAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

I have debugged the binaries to shed some light on the matter and I am still totally lost and I suspect based on my findings that the sdk does not support this scenario.

**URL of the docs**
https://github.com/dapr/docs/issues/new?assignees=&labels=needs-triage%2Ccontent%2Fincorrect-information&projects=&template=wrong-information-code-steps.md&title=

**Expected content**
I would expect that the documentation describes limitations, and more details explaining how to do configure this feature with and withouth the use of the SDK, and perhaps a reference to examples per each technology. If this feature is not available in any given sdk, I think it should be relevant to mention it.

**Screenshots**

**Additional context**
I provided a copy of the source code I am using.
[svc-to-svc.zip](https://github.com/dapr/docs/files/14142542/svc-to-svc.zip)

1. The projects are self explanatory. **dapr.service** uses dapr, **nondapr.servic**e does not use dapr. Solution file is inside dapr.service.

2. I spinup a dapr sidecar for dapr.service using the following comand:
`dapr run --app-id "dapr-service" --app-port "5002" --dapr-grpc-port "50020" --dapr-http-port "5020" --log-level debug -- dotnet run --urls="http://+:5002" --resources-path ..\Resources`
3. I invoke dapr.service through postman using the following request:
```
http://localhost:5020/v1.0/invoke/dapr-service/method/multiply

Body:
{
    "value1":"25",
    "value2":"60"
}
```

4. I am running nondapr.service from Visual Studio 2022 (non debug). I can successfully reach out to the enpoint through postman with the following request:

```
http://localhost:5076/multiply

Body:
{
    "value1":"25",
    "value2":"60"
}
```

**Comment by msfussell** [comment]
For starter this sample should help you https://github.com/dapr/samples/tree/master/workflow-external-invocation
In particular look at the code here https://github.com/dapr/samples/blob/b8328b81846056765874a5ce09fd847dee005f73/workflow-external-invocation/CheckoutService/Activities/ProcessPaymentActivity.cs#L21

Most importantly you have to use
`DaprClient.CreateInvokeHttpClient(appId: "myappname");` you should not use the `InvokeMethodAsync`

Also can you update the URL of the doc link that you were referencing above. This is currently pointing to the issue template. 

Your feedback is welcome and will look to see how to make the docs better for SDK usage. However each of the SDKs have slightly different usage that is specific to each depending on the language.

**Comment by olitomlinson** [comment]
@creyes432 

The problem here is a malformed dapr run command.

`dapr run --app-id "dapr-service" --app-port "5002" --dapr-grpc-port "50020" --dapr-http-port "5020" --log-level debug -- dotnet run --urls="http://+:5002" --resources-path \Resources`

If I check the metadata of the sidecar by calling `http://localhost:5020/v1.0/metadata` I can see that the appCommand is : `"dotnet run --urls=http://+:5002 --resources-path Resources",`

So your custom dapr `Resources` path is not being picked up, and therefore your `endpoint.yaml` is not being loaded.

if you change the dapr run command so that the `--resources-path Resources` isn't the final argument, then it works just fine : 

`dapr run --app-id "dapr-service" --app-port "5002" --dapr-grpc-port "50020" --dapr-http-port "5020" --log-level debug --resources-path Resources -- dotnet run --urls="http://+:5002"`

To validate, call the metadata endpoint again, and you can see that the multiply-service  httpEndpoints has been loaded

```
{
    "id": "dapr-service",
    "runtimeVersion": "1.12.3",
    "components": [
        {
            "name": "dapr",
            "type": "workflow.dapr",
            "version": "v1"
        }
    ],
    "extended": {
        "appCommand": "dotnet run --urls=http://+:5002",
        "appPID": "70735",
        "cliPID": "70731",
        "daprRuntimeVersion": "1.12.3"
    },
    "httpEndpoints": [
        {
            "name": "multiply-service"
        }
    ],
    "appConnectionProperties": {
        "port": 5002,
        "protocol": "http",
        "channelAddress": "127.0.0.1"
    }
}
```

I've attached 3 screenshots, calling various APIs, all resulting in the desired & correct behavior.

![image](https://github.com/dapr/docs/assets/4224880/e7bafa0b-e0f3-43c8-928b-3e6ded044836)
![image](https://github.com/dapr/docs/assets/4224880/d7d88a9f-9bdd-40c2-97f2-82d8b068ffdb)
![image](https://github.com/dapr/docs/assets/4224880/48679761-1d89-4b36-9a87-d826f415ef1c)
