### ISSUE TITLE
Create a new doc that specifically describes use cases

### ISSUE THREAD

**Issue by arschles** [dapr/docs#451]
## Describe the proposal

The [how to](https://github.com/dapr/docs/blob/master/howto/README.md) README has headers in it that allude to use cases, but you have to dig deeper to learn what the use case actually is.

For example, the [Service Invocation](https://github.com/dapr/docs/blob/master/howto/README.md#service-invocation) header makes some sense if you already know what "service invocation" means. If you don't, or you want to learn exactly what it means in Dapr, you have to click through to the [Service Invocation README](https://github.com/dapr/docs/tree/master/howto/invoke-and-discover-services). 

I think it would be beneficial to have a document that specifically briefly details each use case.

**Comment by arschles** [comment]
I will work on this

**Comment by orizohar** [comment]
I don't think terms we use to describe building blocks (such as service invocation) are considered use cases. A use case in my view is something that speaks to a solution a customer is building and includes dimensions like hosting environment, industry etc. For example, a use case would be - "a highly scaled sensor telemetry  IoT solution on edge devices".

I think this kind of content would be better placed in the [concepts README.md](https://github.com/dapr/docs/tree/master/concepts). There is already some description of each of these in the building blocks table. I would encourage you to integrate this more detailed content in there rather than create a new section in the docs.

**Comment by arschles** [comment]
@orizohar under each concept, I described the scenarios in which you might want to use it. I could reverse that, and make each scenario the main section. Thoughts on that?

**Comment by orizohar** [comment]
> @orizohar under each concept, I described the scenarios in which you might want to use it. I could reverse that, and make each scenario the main section. Thoughts on that?

Yes, it would be better to do the reverse and add that extra details in the concepts. I rather we don't introduce a new section in the docs if we don't need to.
