### ISSUE TITLE
Create the guideline to use Service Mesh with Dapr

### ISSUE THREAD

**Issue by amanbha** [dapr/docs#459]
## Describe the proposal
We need to provide the guideline and best practice for users who want to use Service Mesh with Dapr. We need to have test result by running actions with service meshes and provide the instructions.

Copied from https://github.com/dapr/dapr/issues/467

**Comment by msfussell** [comment]
@orizohar - Given the community call today, this would be good to get into the docs

**Comment by GaiusRed** [comment]
Any news on best practices with service mesh? Our deployment environment specifically has istio, but any guidance would be welcome.

**Comment by tomkerkhove** [comment]
Agreed. It looks like the sidecars are managing everything for [Service Invocation](https://github.com/dapr/docs/blob/master/concepts/service-invocation/README.md) component but would be good to learn why we should use that over a service mesh because that's not clear in the [FAQ](https://github.com/dapr/dapr/wiki/FAQ) imo.

Even then, it's hard to scale based on the current solution which could be improved if it would comply with [SMI Spec as per FAQ](https://github.com/dapr/dapr/wiki/FAQ#how-does-dapr-interoperate-with-the-service-mesh-interface-smi) and use something like KEDA to scale on.

**Comment by ipfans** [comment]
Is it possible for the self-hosted mode to run dapr-mesh(or with other service-mesh toolkit)? If so, would you consider providing guidelines for this?

K8s typically runs the dapr runtime in container-based environment. But It still have many services still running without containers. They may need to use dapr-mesh, including to communicate with K8s services, to make it easier to migrate K8s services in the future.

**Comment by AaronCrawfis** [comment]
Partly addressed by https://github.com/dapr/docs/pull/1350

**Comment by AaronCrawfis** [comment]
> Is it possible for the self-hosted mode to run dapr-mesh(or with other service-mesh toolkit)? If so, would you consider providing guidelines for this?
> 
> K8s typically runs the dapr runtime in container-based environment. But It still have many services still running without containers. They may need to use dapr-mesh, including to communicate with K8s services, to make it easier to migrate K8s services in the future.

We currently do not provide any guidance on running service meshes on self-hosted mode. We only support service meshes on Kubernetes: https://docs.dapr.io/concepts/service-mesh/

We're happy to discuss this on the https://aka.ms/dapr-discord server if you want to try it out. We'd also love to eventually add docs on self-hosted service meshes if you'd like to contribute.
