### ISSUE TITLE
Support KiND cluster for local dev environment

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#800]
## Describe the proposal

This is the proposal to support [KiND](https://kind.sigs.k8s.io/). Unlike Minikube, KiND is running all k8s controllers in the single docker container so that it require to create VM.

- [ ] Provide the document to use KiND for local dev environment
- [ ] Update sample docs to support KiND

**Comment by msfussell** [comment]
Update the docs to say KIND cluster is supported

**Comment by yaron2** [comment]
@tcnghia is this done?

**Comment by tcnghia** [comment]
Since there is no bridge to `docker0` network on a Mac (and maybe also Windows), none of the KinD IPs (nodes, LoadBalancers) are accessible from the host network. Currently, this is one thing our e2e tests are assuming. We can change the e2e tests to use port-forwarding instead. I see that we already have the facilities in the code.

On the doc side, we can always instruct te users to use `kubectl port-forward` (already done so in many places), so it isn't a problem.

**Comment by AaronCrawfis** [comment]
This is where it can be placed: https://docs.dapr.io/operations/hosting/kubernetes/cluster/

**Comment by robsondepaula** [comment]
Hello @tcnghia, please check if this WIP https://github.com/dapr/docs/pull/2038 is of some help for this task.

**Comment by yaron2** [comment]
Thanks for taking this on @robsondepaula, PR looks great.

**Comment by robsondepaula** [comment]
Thanks for the feedback @yaron2, PR updated.
