### ISSUE TITLE
"Developing applications" vs "Operations" is confusing

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#917]
I'm struggling a bit with the docs navigation. 
Specifically, I was looking for the list of supported bindings, and noticed they are under "operations" and not "developing applications". There is _some_ bindings info under each, but it isn't clear to me how they are divided. Wouldn't it be much better to have a single place where all information on a topic (such as bindings) is organized? 

a topic called "operations" would in my head indicate subjects around logging, metrics and all other "post-deploy" related things.

**Comment by AaronCrawfis** [comment]
Thanks for the feedback! I agree, we started by placing our existing material into the two categories and are now working to create smarter buckets and organization as we refine the docs experience.

Would you prefer all the bindings and their information to go under "References", or is there another place you feel they would better exist?

**Comment by trondhindenes** [comment]
I really like the structure under "developing applications", imho all content could be organized under there. Taking pub/sub as an example, that would mean that https://v1-rc1.docs.dapr.io/operations/components/setup-pubsub/ (and all "children") would be moved to/merged with https://v1-rc1.docs.dapr.io/developing-applications/building-blocks/pubsub/. 

This would give viewers a single place to find all the needed documentation for pubsub, how to implement it, how to configure the supported pubsub implementations, etc.

A separate "reference" section with all the nitty gritty details is fine, so that can stay where it is.

(realising as I'm writing: This is only my 2 cents, and a Microsoft-backed project like dapr probably has access to people way more knowledgeable than me when it comes to good doc organization)

**Comment by orizohar** [comment]
Sharing some of the thinking around why components are under "operations" - for some users, there is a separation of concerns between the developer that uses the building block API and the operator who chooses which implementation to use when deploying the same code to different environments. One of the benefits of Dapr is that a developer can write their code without thinking of the actual implementation for pub/sub, state, secret etc.
However, I understand the confusion since as a starting point most developers need to be aware of components and configure them at least in the dev environment...
